#!/bin/bash

folders=(
  "./tests/testPrograms/headerParsing/"
  "./tests/testPrograms/methodParsing/"
  "./tests/testPrograms/versionParsing/"
  "./tests/testPrograms/withConfig/"
)

for folder in "${folders[@]}"; do
  echo "echo make -C " $folder
done

for folder in "${folders[@]}"; do
  echo "./test > output" $folder
done

for folder in "${folders[@]}"; do
  echo "echo make fclean -C " $folder
done

echo ./tests/testPrograms/headerParsing/ "test Config.conf" >

echo ./tests/testPrograms/headerParsing/
