# - listen
# - root
# - allow_methods
# - index -> fallback
# - mime_types -> fallback

server {
    listen 0.0.0.0:8080;
    root /var/www/html;

    server_name localhost;
    index index.html;
    client_max_header_size 8192;
    client_max_body_size 1m;
    default_type application/octet-stream;
    error_page 404 /404.html;

    allow_methods GET POST DELETE;
    cgi_support off;
    cgi_path "very cute doggo";
    return 301 https://example.com$request_uri;

    location /images {
        root /var/www/images;
        allow_methods GET;
        autoindex on;
    }

    location /upload {
        root /var/www/upload;
        allow_methods POST;
    }
    include mime.types cgi.types;
}


server {
    listen 8989;
    server_name localhost;
    root /var/www/html;
    index index.html;
    client_max_body_size 1000000;

    error_page 404 /404.html;
    allow_methods GET POST DELETE;

    location /images {
        root /var/www/images;
        allow_methods GET;
        }

    location /upload {
        root /var/www/upload;
        allow_methods POST;
    }

    include mime.types;
}