name: C++98 Web Server CI

on:
  push:
    branches: [ kev ]
  pull_request:
    branches: [ kev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y g++ valgrind

      - name: Compile Web Server (C++98)
        run: g++ -Wall -Werror -Wextra -std=c++98 -g -O0 srcs/*.cpp tests/main.cpp srcs/TestClasses/testUtils.cpp -I ./includes -o webserv

      - name: Compile Unit Tests
        run: |
          g++ -std=c++98 -Wall -Wextra -Werror -g -O0 srcs/*.cpp srcs/TestClasses/*.cpp ./damianServer/*.cpp tests/test_parse_method.cpp -I ./includes -o test_parse_method
          g++ -std=c++98 -Wall -Wextra -Werror -g -O0 srcs/*.cpp srcs/TestClasses/*.cpp ./damianServer/*.cpp tests/test_parse_version.cpp -I ./includes -o test_parse_version
          g++ -std=c++98 -Wall -Wextra -Werror -g -O0 srcs/*.cpp srcs/TestClasses/*.cpp ./damianServer/*.cpp tests/test_parse_headers.cpp -I ./includes -o test_parse_headers
          g++ -std=c++98 -Wall -Wextra -Werror -g -O0 srcs/*.cpp srcs/TestClasses/*.cpp ./damianServer/*.cpp tests/test_request_with_config.cpp -I ./includes -o test_request_with_config
      - name: Run Unit Tests
        run: |
          ./test_parse_method
          ./test_parse_version
          ./test_parse_headers