name: C++98 Web Server CI

on:
  push:
    branches: [ kev ]
  pull_request:
    branches: [ kev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y g++ valgrind

      - name: Compile Unit Tests
        run: make
      - name: Run Unit Tests
        run: |
          ./tests/testPrograms/headerParsing/headerTest
          ./tests/testPrograms/methodParsing/methodTest
          ./tests/testPrograms/versionParsing/versionTest
          ./tests/testPrograms/withConfig/configTest